from __future__ import annotations

from cache_paths import TWIR_PROVIDER_KEY
from constants.base_constants import BaseConstants
from constants.models import (
    CacheNamespaceConfig,
    CoverConfig,
    EpisodeLayoutConfig,
    FeatureListConfig,
    FeatureListKind,
    OutputConfig,
    PodcastConstants,
    TextConfig,
    TocConfig,
)
from podcasts.common.page_constants import (
    COVER_SUB_TEXT,
    EPISODE_AIRDATE_Y,
    EPISODE_DESCRIPTION_Y,
    EPISODE_HEADING_LINE_SPACING,
    EPISODE_IMAGE_WIDTH,
    EPISODE_LISTEN_LABEL_Y,
    EPISODE_TEXT_Y_CM,
    HEADING_LETTERS_PER_LINE,
    LISTEN_IMAGE,
    LISTEN_IMAGE_WIDTH,
    LISTEN_IMAGE_Y,
    NULL_LINK,
    SUB_HEADING_FONT,
    SUB_HEADING_FONT_SIZE,
    SUB_HEADING_X,
    SUB_HEADING_Y_DELTA,
    SUBTLE_TEXT_COLOUR,
    TOC_BOOKMARK,
    TOC_TEXT,
)
from podcasts.twir.page_constants import (
    COVER_IMAGE,
    COVER_LINK,
    COVER_TEXT,
    CSV_LOCATION,
    DEFAULT_FONT_BOLD,
    EPISODE_HEADING_FONT_COLOUR,
    EPISODE_QOW_Y,
    PDF_LOCATION,
    PDF_NAME,
    QOW_LIST_BOOKMARK,
    QOW_LIST_FONT_COLOUR,
    QOW_LIST_FONT_SIZE,
    QOW_LIST_HEADING_FONT_COLOUR,
    QOW_LIST_SPACING_DELTA,
    QOW_LIST_TEXT,
    TOC_FONT_COLOUR,
    TOC_FONT_SIZE,
    TOC_HEADING_FONT_COLOUR,
    TOC_SPACING_DELTA,
)

_BASE = BaseConstants()


def build_twir_constants() -> PodcastConstants:
    csv_name = CSV_LOCATION.rsplit("/", 1)[-1]

    return PodcastConstants(
        provider_key=TWIR_PROVIDER_KEY,
        display_name="This Week in Retro",
        output=OutputConfig(
            pdf_name=PDF_NAME,
            pdf_location=PDF_LOCATION,
            csv_enabled=True,
            csv_name=csv_name,
        ),
        cover=CoverConfig(
            image_url=COVER_IMAGE,
            title_text=COVER_TEXT,
            subtitle_text=COVER_SUB_TEXT,
            title_font_size=_BASE.cover_font_size,
            title_colour=_BASE.cover_font_colour,
            image_width=_BASE.cover_image_width,
            link_url=COVER_LINK,
            title_y=_BASE.cover_title_y,
            subtitle_y=_BASE.cover_subtitle_y,
        ),
        toc=TocConfig(
            title_text=TOC_TEXT,
            font_name=DEFAULT_FONT_BOLD,
            font_size=TOC_FONT_SIZE,
            font_colour=TOC_FONT_COLOUR,
            spacing_delta=TOC_SPACING_DELTA,
            bookmark_name=TOC_BOOKMARK,
            heading_colour=TOC_HEADING_FONT_COLOUR,
            jump_text="[Jump to TOC]",
        ),
        episode_layout=EpisodeLayoutConfig(
            image_width=EPISODE_IMAGE_WIDTH,
            title_y=EPISODE_TEXT_Y_CM,
            title_font_size=_BASE.episode_title_font_size,
            title_colour=EPISODE_HEADING_FONT_COLOUR,
            heading_line_spacing=EPISODE_HEADING_LINE_SPACING,
            description_y=EPISODE_DESCRIPTION_Y,
            metadata_label_y=EPISODE_QOW_Y,
            metadata_value_y=EPISODE_AIRDATE_Y,
            listen_label_y=EPISODE_LISTEN_LABEL_Y,
            listen_image_url=LISTEN_IMAGE,
            listen_image_width=LISTEN_IMAGE_WIDTH,
            listen_image_y=LISTEN_IMAGE_Y,
        ),
        text=TextConfig(
            sub_heading_font=SUB_HEADING_FONT,
            sub_heading_size=SUB_HEADING_FONT_SIZE,
            sub_heading_x=SUB_HEADING_X,
            sub_heading_y_delta=SUB_HEADING_Y_DELTA,
            body_chars_per_line=92,
            heading_chars_per_line=HEADING_LETTERS_PER_LINE,
            subtle_colour=SUBTLE_TEXT_COLOUR,
            null_link=NULL_LINK,
        ),
        feature_list=FeatureListConfig(
            list_kind=FeatureListKind.QOW,
            heading_text=QOW_LIST_TEXT,
            heading_font_size=QOW_LIST_FONT_SIZE,
            heading_colour=QOW_LIST_HEADING_FONT_COLOUR,
            row_font_size=QOW_LIST_FONT_SIZE,
            row_colour=QOW_LIST_FONT_COLOUR,
            spacing_delta=QOW_LIST_SPACING_DELTA,
            bookmark_name=QOW_LIST_BOOKMARK,
        ),
        cache=CacheNamespaceConfig(
            provider_key=TWIR_PROVIDER_KEY,
            image_dir_name="images",
            pickle_keys=("qow_cache",),
            json_keys=("episodes",),
        ),
    )
