from __future__ import annotations

from constants.base_constants import BaseConstants
from constants.models import (
    CacheNamespaceConfig,
    CoverConfig,
    EpisodeLayoutConfig,
    FeatureListConfig,
    FeatureListKind,
    OutputConfig,
    PodcastConstants,
    TextConfig,
    TocConfig,
)
from podcasts.zttp.page_constants import (
    COVER_IMAGE,
    COVER_LINK,
    COVER_SUB_TEXT,
    COVER_TEXT,
    DEFAULT_FONT_BOLD,
    EPISODE_FONT_COLOUR,
    EPISODE_FONT_SIZE,
    EPISODE_IMAGE_WIDTH,
    EPISODE_TEXT_Y_CM,
    GAME_LIST_BOOKMARK,
    GAME_LIST_FONT_COLOUR,
    GAME_LIST_FONT_SIZE,
    GAME_LIST_SPACING_DELTA,
    GAME_LIST_TEXT,
    LISTEN_IMAGE,
    LISTEN_IMAGE_WIDTH,
    LISTEN_IMAGE_Y,
    NULL_LINK,
    PDF_LOCATION,
    PDF_NAME,
    SUB_HEADINGS_LETTERS_PER_LINE,
    SUB_HEADING_FONT,
    SUB_HEADING_FONT_SIZE,
    SUB_HEADING_X,
    SUB_HEADING_Y_DELTA,
    SUBTLE_TEXT_COLOUR,
    TOC_BOOKMARK,
    TOC_FONT_COLOUR,
    TOC_FONT_SIZE,
    TOC_SPACING_DELTA,
    TOC_TEXT,
)

_BASE = BaseConstants()


def build_zttp_constants() -> PodcastConstants:
    return PodcastConstants(
        provider_key="ZTTP",
        display_name="Zapped to the Past",
        output=OutputConfig(
            pdf_name=PDF_NAME,
            pdf_location=PDF_LOCATION,
            csv_enabled=False,
            csv_name=None,
        ),
        cover=CoverConfig(
            image_url=COVER_IMAGE,
            title_text=COVER_TEXT,
            subtitle_text=COVER_SUB_TEXT,
            title_font_size=_BASE.cover_font_size,
            title_colour=_BASE.cover_font_colour,
            image_width=_BASE.cover_image_width,
            link_url=COVER_LINK,
            title_y=_BASE.cover_title_y,
            subtitle_y=_BASE.cover_subtitle_y,
        ),
        toc=TocConfig(
            title_text=TOC_TEXT,
            font_name=DEFAULT_FONT_BOLD,
            font_size=TOC_FONT_SIZE,
            font_colour=TOC_FONT_COLOUR,
            spacing_delta=TOC_SPACING_DELTA,
            bookmark_name=TOC_BOOKMARK,
            heading_colour=None,
            jump_text="[Jump to TOC]",
        ),
        episode_layout=EpisodeLayoutConfig(
            image_width=EPISODE_IMAGE_WIDTH,
            title_y=EPISODE_TEXT_Y_CM,
            title_font_size=EPISODE_FONT_SIZE,
            title_colour=EPISODE_FONT_COLOUR,
            heading_line_spacing=0.6,
            description_y=29.2 - 2,
            metadata_label_y=29.2 - 21,
            metadata_value_y=29.2 - 22,
            listen_label_y=LISTEN_IMAGE_Y - 2.8,
            listen_image_url=LISTEN_IMAGE,
            listen_image_width=LISTEN_IMAGE_WIDTH,
            listen_image_y=LISTEN_IMAGE_Y,
        ),
        text=TextConfig(
            sub_heading_font=SUB_HEADING_FONT,
            sub_heading_size=SUB_HEADING_FONT_SIZE,
            sub_heading_x=SUB_HEADING_X,
            sub_heading_y_delta=SUB_HEADING_Y_DELTA,
            body_chars_per_line=SUB_HEADINGS_LETTERS_PER_LINE,
            heading_chars_per_line=None,
            subtle_colour=SUBTLE_TEXT_COLOUR,
            null_link=NULL_LINK,
        ),
        feature_list=FeatureListConfig(
            list_kind=FeatureListKind.GAME_LIST,
            heading_text=GAME_LIST_TEXT,
            heading_font_size=GAME_LIST_FONT_SIZE,
            heading_colour=GAME_LIST_FONT_COLOUR,
            row_font_size=GAME_LIST_FONT_SIZE,
            row_colour=GAME_LIST_FONT_COLOUR,
            spacing_delta=GAME_LIST_SPACING_DELTA,
            bookmark_name=GAME_LIST_BOOKMARK,
        ),
        cache=CacheNamespaceConfig(
            provider_key="ZTTP",
            image_dir_name="images",
            pickle_keys=("episode_cache", "zzap_cache", "crapverts_cache"),
            json_keys=(),
        ),
    )
