TEXT_TO_REMOVE = [
    "will upload info later",
    "ep 81",
    "ep80",
    "Hello there retro gaming fans, welcome back to another fun filled Ep of RGDS",
    "Welcome to another fun filled episode of RGDS",
    "Please note:- There are 2 versions of this episode; the stereo mix is done in a cinematic way to celebrate the movies. If you, for whatever reason, require the mono version - please choose that one For best listening experience use headphones in a dark room with some alcoholic beverages of your choice",
]

TEXT_TO_STOP_AT = [
    "Games list:",
    "Games on the show:",
    "The games are:",
    "You can follow me on Twitter",
    "Don't forget to check out our YouTube channel with video versions of the podcast",
    "The games covered:",
    "The games covered in this episode:",
    "Links:",
    "Show notes:",
    "Show Note Links",
    "You can follow us on Twitter",
    "Games covered in this episode",
    "You can follow @RGDSPodcast on Twitter",
    "You can follow",
    "Show Notes:",
    "The games discussed in this episode",
    "The games covered in this episode are:",
    "Hosts on the show; Matt Aguilera",
    "Don't forget South Yorkshire Video Game and Collectables Fare",
    "The games covered in the episode are...",
    "*** Welcome to a special episode of RGDS",
    "If you enjoy this ep then please follow the lads on Twitter",
    "But we want to hear from our listeners.",
    "If you enjoy this ep then please follow",
    "Credit to Jackson Taylor",
    "RGDS is also now available on iTunes",
    "Credit to the following great musicians",
    "Check out the Kickstarter page",
    "#KeepItImport @Lambomat @RGDSPodcast",
    "The games included are:",
    "Games featured in this episode are:",
    "Games featured in the episode are",
    "Games covered are:",
    "Combat Hack Red vs Blue",
    "The Games covered:",
    "Games features in this episode:",
    "Games Super Tempo :",
    "Hidden Gems:",
    "Mortal Kombat II Unlimited",
    "Supercade Book 2 :",
    "SPOILERS GAMES AND MOVIES COVERED",
    "Games in this episode:",
    "The games covered are:-",
    "Here are the first 50 games in the first part:",
    "The games we have picked out from this amazing collection are:",
    "Games in this episode are:",
    "Please join us on our You Tube channel here:",
    "Games on the episode:",
    "Be sure to check out the links below",
    "Show Notes ",
    "X-Arcade:",
    "GAMES ADVENTURES OF BATMAN & ROBIN",
    "Japanese Arcade Rhythm Games Check out some of the games Garron mentions on the show",
    "The featured games are:",
    "@RGDSPodcast @Gettwodachoppa @RetroShumper @Lambomat @RetroRic79",
    "Here are the links:",
    "Follow RGDS on Twitter",
    "The chosen games were",
    "Games Covered:",
    "Show notes ",
    " Contact us -",
    "Amiga Mini:",
    "Notes - ",
    "Matt has shared his awesome Apple Music Crazy Taxi playlist",
    "COMPETITION To enter the competition",
    "Show links:-",
    "Dragontorc influence - The High Kings by Joy Chant",
    "The centre of computing history has",
    "all systems being played",
    "Games featured in this episode:",
    "https://archive.org/details/rgds-amiga-top-50-games-2-v-3-book-one-50-26-7-jun",
    "With thanks to Gary Arnott for recreating that",
    "The shows/games featured in this episode are:",
    "1. slipstream 5000 2. whiplash 3. Actua Soccer",
    "The Games:",
    "Games covered:",
    "Follow us @RGDSPodcast",
    "Games covered are;",
    "3D VR NES",
    "Ant Stream Kickstarter:",
    "6 months before a PAL release, and Matt A had a few nightmares he d like to forget about. We also give a quick run through some of the games that inspired the original RE",
    "Games covered in the episode are:-",
    "Follow the team on twitter",
    "This is a fascinating conversation",
    "Popular opinion during their heyday",
    "Resident RGDS host Matt Aguilera",
    "Ways to Contact Us",
    "We have also collected up these amazing games",
    "Contact Us:",
    "If you listened to it last year",
    "We are also joined by special guest",
    "We hope this will get you excited about",
    "LINKS - Sonic Mania",
    "Take a look at so of the great content",
    "Reach out to us on on twitter",
    "Colin's story is a",
    "Graphics 5/5 Sound 5/5",
    "If you would like to follow Julian hill on Twitter",
    "Links -",
    "Find out who won the amazing prize?",
    "Also please take a few moments to check our amazing",
    "Also the RGDS team was hoping you could help us out",
    "The song at the end of the podcast is",
    "Big thanks toThe Oliver",
    "Book 2:",
    "Bitmap Books have kindly made one of the Collector",
    "Also Chris Wilkins writer of the superb book",
    "Games featured in episode: Astronut - Software Projects",
]
